server:
  port: 8080

logging:
  level:
    root: INFO
    com.tanadelgigante: DEBUG

spring:
  cloud:
    gateway:
      default-filters:
        - name: FlexibleAuthenticationFilter
      routes:
        - id: example-service-1
          uri: http://example-service-1:5000
          predicates:
            - Path=/example1/**
          filters:
            - StripPrefix=1
        - id: example-service-2
          uri: http://example-service-2:4000
          predicates:
            - Path=/example2/**
          filters:
            - StripPrefix=1
