services:
  civil-servant:
    build: .
    ports:
      - "8187:8080"
    networks:
      - gateway-network
    volumes:
      - /path/to/dir:/container/dir

networks:
  gateway-network:
    driver: bridge
